#!/bin/bash

# TODO: Make arguments can be flagged so don't have to use hardcoded argument indexes. Lookup getopts.

# Getting remote origin from first argument.
REPO_ORIGIN=$1

# Getting project name from current folder name, if there is a second parameter, use that instead.
# Also, modify the string so it conforms Github repository name convention. (All lowercase, hypen '-' instead of whitespace ' ')
PROJECT_NAME=${PWD##*/}
if [ -n "$2" ]; then
    PROJECT_NAME=$2
fi
PROJECT_NAME="${PROJECT_NAME// /-}"
PROJECT_NAME=${PROJECT_NAME,,}

# Commit message default to "first commit", if there is a third parameter, use that instead.
COMMIT_MESSAGE="first commit"
if [ -n "$3" ]; then
    COMMIT_MESSAGE=$3
fi

# Initializing git
git init

# Creating README.md file and writing project name to it.
echo " # $PROJECT_NAME" >>README.md

# Creating .gitignore file and writing classic Unity.gitignore.
# TODO: Somehow get latest from https://github.com/github/gitignore/blob/master/Unity.gitignore, and delete this wall of string.
echo "# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/master/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# Temporary auto-generated Android Assets
/[Aa]ssets/[Ss]treamingAssets/aa.meta
/[Aa]ssets/[Ss]treamingAssets/aa/*" >>.gitignore

# Add, commit and push to origin.
git add .
git commit -m "$COMMIT_MESSAGE"
git branch -M main
git remote add origin "$REPO_ORIGIN"
git push -u origin main
